OPENAI_API_KEY = "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"
PINECONE_API_KEY = "pcsk_5vX8Gt_3Qt5Fe9z3ys24JU9xp99F3irB5a7EizQETWB9k1K7zUgB6HLGoJheEgxDPpXQur"
PINECONE_INDEX_NAME = "machine-learning-textbook"